### ISSUE TITLE
Project Template Descriptions need to be updated

### ISSUE THREAD

**Issue by sgiffinlcd** [CodeFactoryLLC/CodeFactory#10]
The current project descriptions for the automation and command project templates is confusing. Needs to be clarified and updated.

**Comment by sgiffinlcd** [comment]
@jhannahLCD  please provide the easy to understand descriptions for each project template. I will get this loaded into the next SDK  build.

**Comment by sgiffinlcd** [comment]
@jhannahLCD Please begin this task since im opening up the SDK. I would like to update the project descriptions by end of day 8-12-2020

**Comment by jhannahLCD** [comment]
@sgiffinlcd want me to update the code directly? or just post the edits here?

**Comment by sgiffinlcd** [comment]
You can post the new descriptions for each project template directly here in the issue Ill add the updates once i crack open the SDK.

Thanks

**Comment by sgiffinlcd** [comment]
@jhannahLCD temp verbiage for the 230 SDK release

Command Library - CodeFactory project that hosts all commands that trigger automation in Visual Studio.
Automation Library - CodeFactory project that hosts common functionality that can be consumed by one or more CodeFactory command projects.

**Comment by jhannahLCD** [comment]
@sgiffinlcd slightly edited

Command Library - A CodeFactory project that hosts all automation commands which are triggered from within Visual Studio Solution Explorer.
Automation Library -  A CodeFactory project that hosts common functionality which can be consumed by one or more CodeFactory Command Library projects.

**Comment by sgiffinlcd** [comment]
Have added to the 1.0.20230.1 build
