### ISSUE TITLE
NullReferenceException Loading Test Application

### ISSUE THREAD

**Issue by RealDotNetDave** [CodeFactoryLLC/CodeFactory#15]
Today, while trying to load the text project for my CodeFactory commands, I am getting this error:

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=NuGet.Tools
  StackTrace:
   at NuGetVSExtension.NuGetPackage.<>c__DisplayClass85_0.<<BeforeQueryStatusForAddPackageForSolutionDialog>b__0>d.MoveNext()
```

I did update VS2019 this week to version 16.8.5.

**Comment by sgiffinlcd** [comment]
@RealDotNetDave which test project type where you using? also can you give me some basic information on the setup of the test project so I can recreate it? 
Thanks

**Comment by sgiffinlcd** [comment]
Have talked with @RealDotNetDave about the issue and determined that this is an enhancement need to be added to the Visual Studio Runtime for CodeFactory. Have created #17 to address this need. Has been moved into the backlog for delivery.
