### ISSUE TITLE
Links in README.md are broken

### ISSUE THREAD

**Issue by MisinformedDNA** [CodeFactoryLLC/CodeFactory#34]
The following links result in 404s:

- [CodeFactory Overview](https://docs.codefactory.software/guidance/Introduction/Overview.html)

- [CodeFactory Guidance](https://docs.codefactory.software/guidance/howto/Overview.html)

**Comment by jhannahLCD** [comment]
That is not ideal... :)

What hosting page were you coming from that held the broken links?

**Comment by bfencken** [comment]
Need to update readme.md on this page John. Second two links are not connecting to the recently updated docs. 
https://github.com/CodeFactoryLLC/CodeFactory/blob/42b6daab4f7d83e7a4a13c6888f66fb1ec9d575c/README.md

**Comment by bfencken** [comment]
Links updated. Thanks for the report @MisinformedDNA
