### ISSUE TITLE
Can CodeFactory identify which framework is being used?

### ISSUE THREAD

**Issue by bfencken** [CodeFactoryLLC/CodeFactory#8]
When CodeFactory is accessing existing code, can it identify which framework the code is using (i.e. Clr, Core, .NET 5 etc.)?
(Thanks for the question @realdotnetdave !)

**Comment by sgiffinlcd** [comment]
At this time we do not have direct access to this information from the project system. You can use project references to infer the information. We are watching for the project system updates to see if this meta data will be available in the future. If the functionality becomes available will add it to the queue. Also a great request, this is something I also want in the future 👍

**Comment by RealDotNetDave** [comment]
I'm implementing this like the example below that uses my open-source project:

```
                    if (App.FrameworkDescription.StartsWith(".NET 5."))
                    {
                        ProcessDotNetParams(param, source, formatter, method);
                    }
                    else
                    {
                        ProcessDotNetClrParams(param, source, formatter, method);
                    }
```
It would be useful to just have a method that returns something like NetClr, NetCore, Net, or something else. Then another method that returns the actual version number like 5.0.4.

**Comment by sgiffinlcd** [comment]
Sure does @RealDotNetDave , that is already in the lastest release.

You have the TargetFrameworks property on the VSProject model. 
https://docs.codefactory.software/api/CodeFactory.VisualStudio.VsProject.html#CodeFactory_VisualStudio_VsProject_TargetFrameworks

This will give you back an Array of VSProjectFramework model
https://docs.codefactory.software/api/CodeFactory.VisualStudio.VsProjectFramework.html

This will tell you if it is .net core or .net framework and the target version the project outputs.
